baseURL = "http://codystumpo.github.io/"
languageCode = "en-us"
title = "Cody Stumpo"
theme = "creative-portfolio"

[params]
 style = "default"
 sidebarAbout = [
 "I fiddle around with applied math problems.",
 "San Mateo, CA"
 ]
  description = "Cody Stumpo's Portfolio"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"


 [params.social]
 linkedin = "https://www.linkedin.com/in/codystumpo/en"
 github = "https://github.com/CodyStumpo/"
 youtube = "https://www.youtube.com/user/codybass"
